# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_post_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name=b'Name')),
                ('image', s3direct.fields.S3DirectField(blank=True, default=b'', null=True, verbose_name=b'Image')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='transcript',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name=b'Transcript'),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsorImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.SponsorshipImage'),
        ),
    ]
