# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20171229_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipimage',
            name='text',
            field=models.TextField(default=b'', verbose_name=b'Text'),
        ),
        migrations.AddField(
            model_name='sponsorshipimage',
            name='url',
            field=models.TextField(default=b'', verbose_name=b'Text'),
        ),
    ]
