# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20180117_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorshipimage',
            name='url',
        ),
        migrations.AddField(
            model_name='sponsorshipimage',
            name='redirectUrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Redirect Url'),
        ),
        migrations.AlterField(
            model_name='sponsorshipimage',
            name='text',
            field=models.TextField(blank=True, default=b'', null=True, verbose_name=b'Text'),
        ),
    ]
